version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:latest
    container_name: vopros-sfu
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vopros
    ports:
      - "5211:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local
