version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: vopros-sfu
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vopros
    ports:
      - "5211:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
