module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
  transformIgnorePatterns: ['<rootDir>/dist/'],
  moduleFileExtensions: ['ts', 'js', 'json'],
  testMatch: ['<rootDir>/src/tests/**/*.test.ts'],

  collectCoverage: true,
  coverageProvider: 'babel',
  collectCoverageFrom: ['<rootDir>/src/modules/**/*.ts'],
  coveragePathIgnorePatterns: [
    '<rootDir>/node_modules/',
    '<rootDir>/dist/',
    '<rootDir>/src/migrations',
    '<rootDir>/src/files',
    '<rootDir>/src/config',
    '<rootDir>/src/templates',
    '<rootDir>/src/tests',
    '<rootDir>/src/main.ts',
    '<rootDir>/src/modules/.*/domain/dtos',
    '<rootDir>/src/modules/.*/domain/models',
    '<rootDir>/src/modules/.*/domain/interfaces',
    '<rootDir>/src/modules/.*/domain/enums',
    '<rootDir>/src/modules/.*/infrastructure/entities',
    '<rootDir>/src/modules/.*/infrastructure/schemas',
    '<rootDir>/src/modules/.*/infrastructure/.*Module.ts',
    '<rootDir>/src/modules/AppModule.ts',
  ],
};
